# Generated by Django 4.2.7 on 2023-12-11 04:42

import app_color.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', app_color.models.ColorField(default='#FF0000', max_length=7, unique=True, verbose_name='Цвет')),
                ('name_color', models.CharField(default='Красный', max_length=35, unique=True, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
    ]
