# Generated by Django 4.2.7 on 2023-11-08 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0008_alter_products_discount_period'),
        ('app_color', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app_products.products', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
