# Generated by Django 4.2.7 on 2023-11-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_color', '0002_color_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
    ]
