# Generated by Django 4.2.7 on 2023-11-10 07:54

import app_color.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_color', '0003_remove_color_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=app_color.models.ColorField(default='#FF0000', max_length=7, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name_color',
            field=models.CharField(default='Красный', max_length=35, unique=True, verbose_name='Название цвета'),
        ),
    ]
