# Generated by Django 4.2.7 on 2023-12-11 04:42

import app_reviews.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, validators=[app_reviews.models.valid], verbose_name='Оценка/Рейтинг')),
                ('review', models.TextField(max_length=2000, unique=True, verbose_name='Отзыв')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+7\\d{10}$')], verbose_name='Телефонный номер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв/Рейтинг',
                'verbose_name_plural': 'Отзывы/Рейтинги',
            },
        ),
    ]
