# Generated by Django 4.2.7 on 2023-11-08 09:15

import app_reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[app_reviews.models.valid], verbose_name='Оценка/Рейтинг'),
        ),
    ]
