# Generated by Django 4.2.7 on 2023-12-11 04:42

import app_products.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_category', '0001_initial'),
        ('app_promo', '0001_initial'),
        ('app_color', '0001_initial'),
        ('app_tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150, verbose_name='Наименование продукта')),
                ('desc_product', models.TextField(blank=True, max_length=1000, verbose_name='Описание продукта')),
                ('display_price', models.BooleanField(default=False, verbose_name='Отображать цену')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[app_products.models.valid], verbose_name='Цена')),
                ('price_with_discount_or_PROMO', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[app_products.models.valid], verbose_name='Итоговая цена со скидками/ПРОМО')),
                ('display_discount', models.BooleanField(default=False, verbose_name='Отобразить/Применить скидку')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, validators=[app_products.models.valid], verbose_name='Скидка')),
                ('discount_period', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 14, 10, 42, 35, 925212), help_text='По умолчанию +3 дня от времени создания карточки продукта', verbose_name='Действие скидки до')),
                ('display_remaining_goods', models.BooleanField(default=False, verbose_name='Отобразить остаток товара')),
                ('remaining_goods', models.PositiveIntegerField(blank=True, default=0, verbose_name='Остаток товара')),
                ('display_tag', models.BooleanField(default=False, verbose_name='Показывать ТЕГ')),
                ('display_promo', models.BooleanField(default=False, verbose_name='Отобразить/Применить ПРОМО')),
                ('display_reviews', models.BooleanField(default=False, verbose_name='Отображать отзывы/Рейтинг')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, validators=[app_products.models.rating_valid], verbose_name='Рейтинг')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_category.category', verbose_name='Категория продукта')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_color.color', verbose_name='Цвет')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_promo.promo', verbose_name='Участие продукта в промо')),
                ('tag', models.ManyToManyField(blank=True, to='app_tags.tags', verbose_name='ТЕГ')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_images/%Y/%m/%d/%H/%M/%S/', verbose_name='Изображение')),
                ('desc', models.TextField(blank=True, max_length=1500, verbose_name='Описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
