# Generated by Django 4.2.7 on 2023-11-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150, verbose_name='Наименование продукта')),
                ('desc_product', models.TextField(blank=True, max_length=1000, verbose_name='Описание продукта')),
                ('display_price', models.BooleanField(default=False, verbose_name='Отображать цену')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('display_discount', models.BooleanField(default=False, verbose_name='Отобразить скидку')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Скидка')),
                ('display_remaining_goods', models.BooleanField(default=False, verbose_name='Отобразить остаток товара')),
                ('remaining_goods', models.BigIntegerField(default=0, verbose_name='Остаток товара')),
            ],
        ),
    ]
