# Generated by Django 4.2.7 on 2023-11-03 10:23

import app_products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_category', '0001_initial'),
        ('app_tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150, verbose_name='Наименование продукта')),
                ('desc_product', models.TextField(blank=True, max_length=1000, verbose_name='Описание продукта')),
                ('display_price', models.BooleanField(default=False, verbose_name='Отображать цену')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[app_products.models.valid], verbose_name='Цена')),
                ('display_discount', models.BooleanField(default=False, verbose_name='Отобразить скидку')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, validators=[app_products.models.valid], verbose_name='Скидка')),
                ('display_remaining_goods', models.BooleanField(default=False, verbose_name='Отобразить остаток товара')),
                ('remaining_goods', models.PositiveIntegerField(blank=True, default=0, verbose_name='Остаток товара')),
                ('display_tag', models.BooleanField(default=False, verbose_name='Показывать ТЭГ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_category.category', verbose_name='Категория продукта')),
                ('tag', models.ManyToManyField(blank=True, to='app_tags.tags', verbose_name='ТЭГ')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_images/%Y/%m/%d/%H/%M/%S/', verbose_name='Изображение')),
                ('desc', models.TextField(blank=True, max_length=1500, verbose_name='Описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.products', verbose_name='Продукт')),
            ],
        ),
    ]
