# Generated by Django 4.2.7 on 2023-11-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='remaining_goods',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Остаток товара'),
        ),
    ]
