# Generated by Django 4.2.7 on 2023-11-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_promo', '0001_initial'),
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='display_promo',
            field=models.BooleanField(default=False, verbose_name='Отображать ПРОМО'),
        ),
        migrations.AddField(
            model_name='products',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_promo.promo', verbose_name='Участие продукта в промо'),
        ),
    ]
