# Generated by Django 4.2.7 on 2023-11-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_products_display_promo_products_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='display_reviews',
            field=models.BooleanField(default=False, verbose_name='Отображать отзывы'),
        ),
    ]
