# Generated by Django 4.2.7 on 2023-11-03 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0001_initial'),
        ('app_products', '0002_alter_products_discount_alter_products_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_category.category', verbose_name='Категория продукта'),
        ),
    ]
