# Generated by Django 4.2.7 on 2023-11-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_products_display_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, verbose_name='Рейтинг'),
        ),
    ]
