# Generated by Django 4.2.7 on 2023-11-03 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/%d/%H/%M/%S/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.products', verbose_name='Продукт')),
            ],
        ),
    ]
