# Generated by Django 4.2.7 on 2023-11-06 05:23

import app_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_products_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='display_reviews',
            field=models.BooleanField(default=False, verbose_name='Отображать отзывы/Рейтинг'),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, validators=[app_products.models.rating_valid], verbose_name='Рейтинг'),
        ),
    ]
