# Generated by Django 4.2.7 on 2023-11-06 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0006_products_price_with_discount_or_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_period',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 10, 56, 21, 833404), verbose_name='Действие скидки до'),
        ),
        migrations.AlterField(
            model_name='products',
            name='display_promo',
            field=models.BooleanField(default=False, verbose_name='Отобразить/Применить ПРОМО'),
        ),
    ]
