# Generated by Django 4.2.7 on 2023-11-10 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_color', '0003_remove_color_product'),
        ('app_products', '0018_alter_products_discount_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_color.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_period',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 13, 11, 56, 26, 931744), help_text='По умолчанию +3 дня от времени создания карточки продукта', verbose_name='Действие скидки до'),
        ),
    ]
