# Generated by Django 4.2.7 on 2023-12-11 04:42

import app_promo.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_promo', models.CharField(max_length=150, unique=True, verbose_name='Название ПРОМО')),
                ('discount_period_promo', models.DateTimeField(default=datetime.datetime(2023, 12, 14, 10, 42, 35, 924325), help_text='По умолчанию +3 дня от времени создания карточки продукта', verbose_name='Действие скидки ПРОМО до')),
                ('desc_promo', models.TextField(blank=True, max_length=1500, verbose_name='Описание ПРОМО')),
                ('pass_promo', models.CharField(max_length=150, unique=True, verbose_name='ПРОМО слово/ключ/пароль')),
                ('discont_promo', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[app_promo.models.valid], verbose_name='Скидка по ПРОМО')),
            ],
            options={
                'verbose_name': 'Промо',
                'verbose_name_plural': 'Промо',
            },
        ),
    ]
