# Generated by Django 4.2.7 on 2023-11-03 10:38

import app_promo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_promo', models.CharField(max_length=150, unique=True, verbose_name='Название ПРОМО')),
                ('desc_promo', models.TextField(blank=True, max_length=1500, verbose_name='Описание ПРОМО')),
                ('pass_promo', models.CharField(max_length=150, unique=True, verbose_name='ПРОМО слово/ключ/пароль')),
                ('discont_promo', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[app_promo.models.valid], verbose_name='Скидка по ПРОМО')),
            ],
        ),
    ]
