# Generated by Django 4.2.7 on 2023-11-07 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='discount_period_promo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 10, 9, 30, 40, 731492), help_text='По умолчанию +3 дня от времени создания карточки продукта', verbose_name='Действие скидки ПРОМО до'),
        ),
    ]
