# Generated by Django 4.2.7 on 2023-12-11 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount_period_promo',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 11, 2, 53, 492401), help_text='По умолчанию +3 дня от времени создания карточки продукта', verbose_name='Действие скидки ПРОМО до'),
        ),
    ]
