# Generated by Django 4.2.7 on 2023-11-07 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_promo', '0005_alter_promo_discount_period_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount_period_promo',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 16, 14, 32, 140649), help_text='По умолчанию +3 дня от времени создания карточки продукта', verbose_name='Действие скидки ПРОМО до'),
        ),
    ]
