# Generated by Django 4.2.7 on 2023-11-08 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_promo', '0008_alter_promo_discount_period_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount_period_promo',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 15, 14, 24, 488121), help_text='По умолчанию +3 дня от времени создания карточки продукта', verbose_name='Действие скидки ПРОМО до'),
        ),
    ]
