# Generated by Django 4.2.7 on 2023-12-11 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date_and_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата и время и создания')),
                ('user_session', models.CharField(max_length=300, verbose_name='Сессия пользователя')),
                ('user_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя')),
                ('user_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефонный номер')),
                ('order_delivery', models.BooleanField(default=False, verbose_name='Доставка')),
                ('order_delivery_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адресс доставки')),
                ('order_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True, verbose_name='Общая стоимость заказа')),
                ('promo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примененное промо')),
            ],
            options={
                'verbose_name': 'Ордер',
                'verbose_name_plural': 'Ордера',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=300, verbose_name='Сессия пользователя')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество продукта')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('promo_active', models.BooleanField(default=False, verbose_name='Активировано ПРОМО')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
