# Generated by Django 4.2.7 on 2023-12-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0002_remove_order_creation_date_and_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_product_list',
            field=models.JSONField(blank=True, default={}, editable=False, null=True, verbose_name='Продукты данного заказа'),
        ),
    ]
