# Generated by Django 4.2.7 on 2023-12-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0003_order_order_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creation_date_and_time',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата и время и создания'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Примененное промо'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_product_list',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True, verbose_name='Продукты данного заказа'),
        ),
    ]
