# Generated by Django 4.2.7 on 2023-11-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0003_basket_total_cost_pos_alter_basket_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_cost_pos',
        ),
    ]
