# Generated by Django 4.2.7 on 2023-12-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0004_order_creation_date_and_time_order_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, help_text='\n        Когда заявка исполнена выбрать данный параметр и сохранить запись.\n        ', verbose_name='Заявка исполнена?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_product_list',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Продукты данного заказа'),
        ),
    ]
