# Generated by Django 4.2.7 on 2023-11-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0004_remove_basket_total_cost_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='basket',
            name='user_session',
            field=models.CharField(default='jq4hmz573cskhbyeufligog12q15iaqq', max_length=300, verbose_name='Сессия пользователя'),
            preserve_default=False,
        ),
    ]
