# Generated by Django 4.2.7 on 2023-11-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0005_remove_basket_phone_number_basket_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user_session',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Сессия пользователя'),
        ),
    ]
