# Generated by Django 4.2.7 on 2023-11-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0006_alter_basket_user_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='user_session',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True, verbose_name='Сессия пользователя'),
        ),
    ]
