# Generated by Django 4.2.7 on 2023-11-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0007_alter_basket_options_alter_basket_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user_session',
            field=models.CharField(default='jq4hmz573cskhbyeufligog12q15iaqq', max_length=300, verbose_name='Сессия пользователя'),
            preserve_default=False,
        ),
    ]
