# Generated by Django 4.2.7 on 2023-11-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0009_basket_app_basket_basket_user_session_products'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='basket',
            name='app_basket_basket_user_session_products',
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(fields=('user_session', 'products'), name='name___'),
        ),
    ]
