# Generated by Django 4.2.7 on 2023-11-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0010_remove_basket_app_basket_basket_user_session_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user_session',
            field=models.CharField(blank=True, default='No session', editable=False, max_length=300, null=True, verbose_name='Сессия пользователя'),
        ),
    ]
