# Generated by Django 4.2.7 on 2023-11-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0012_remove_basket_name____and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user_session',
            field=models.CharField(blank=True, default='No session', max_length=300, null=True, verbose_name='Сессия пользователя'),
        ),
    ]
