# Generated by Django 4.2.7 on 2023-11-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0014_alter_basket_user_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='basket',
            name='app_basket_basket_user_session_products',
        ),
    ]
