# Generated by Django 4.2.7 on 2023-12-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0016_basket_promo_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=300, verbose_name='Сессия пользователя')),
                ('user_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя')),
                ('user_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефонный номер')),
                ('order_delivery', models.BooleanField(default=False, verbose_name='Доставка')),
                ('order_delivery_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адресс доставки')),
                ('order_total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True, verbose_name='Общая стоимость заказа')),
                ('promo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примененное промо')),
            ],
        ),
    ]
