# Generated by Django 4.2.7 on 2023-12-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0017_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creation_date_and_time',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата и время и создания'),
        ),
    ]
